import { useEffect } from 'react'

const exact = new Map<string, string>([
  ['Screenshot-backed', 'Verified'],
  ['Latest screenshot', 'Verified'],
  ['Supplemental', 'Reviewed'],
  ['Spreadsheet supplement', 'Reviewed'],
  ['Sharandar ZIP', 'Sharandar'],
  ['Final ZIP', 'Underdark'],
  ['Underdark ZIP', 'Underdark'],
  ['Recipe verification & evidence', 'Recipe details'],
  ['Recipe state', 'Review status'],
  ['Source status', 'Record status'],
  ['Source record', 'Reference'],
  ['Recorded direct recipe', 'Direct recipe'],
  ['WORKSHOP REFERENCE', 'MASTERWORK REFERENCE'],
  ['Crafting context beyond the recipe tree', 'Everything you need around the recipe tree'],
])

const phrases: Array<[RegExp, string | ((...args: string[]) => string)]> = [
  [/The supplied screenshot does not show this recipe's output quantity\./gi, 'The output quantity for this recipe is not confirmed yet.'],
  [/The supplied Sharandar screenshot identifies this craftable, but its input recipe is not visible\./gi, 'This craftable is catalogued, but its input recipe is not confirmed yet.'],
  [/The supplied guide/gi, 'The guide'],
  [/the supplied guide/gi, 'the guide'],
  [/The supplied video write-up reconstructs a Module 15 Workshop tutorial and related economic guidance rather than providing a literal transcript\./gi, 'This guide summarizes a historical Module 15 Workshop walkthrough and related community guidance.'],
  [/User-supplied Sharandar screenshots supply new masterwork weapons, armor, materials, potions, supplements, recipes, tooltips, and extracted icons\./gi, 'The Sharandar collection covers masterwork weapons, armor, materials, potions, supplements, recipes, item details, and artwork.'],
  [/The existing Menzoberranzan \/ Underdark ZIP remains intact as a separate collection rather than being overwritten by the Sharandar pack\./gi, 'The Menzoberranzan / Underdark collection remains separate so its recipes and materials stay distinct from Sharandar.'],
  [/Workshop progression, artisan mechanics, South Seas commissions, and source caveats live here so the Sharandar collection does not have to hide important context inside individual weapon cards\./gi, 'Workshop progression, artisan mechanics, South Seas commissions, and collection notes live here so important context stays easy to find.'],
  [/Switch between the existing Underdark catalogue and the new Sharandar screenshot pack without mixing source claims\. Direct recipes, from-scratch expansion, workshop context, and extracted item art stay traceable to their evidence\./gi, 'Switch between Underdark and Sharandar without mixing recipe sets. Direct recipes, from-scratch expansion, workshop context, and item details stay organized by collection.'],
  [/Keep screenshot-backed recipe evidence separate from historical workshop strategy\./gi, 'Keep confirmed recipe data separate from historical workshop strategy.'],
  [/Missing recipe evidence should remain unknown instead of becoming a zero-cost craft\./gi, 'Missing recipe details should remain unknown instead of becoming a zero-cost craft.'],
  [/Neverwinter Workshop Rank 1 → Rank 4 tutorial reconstruction supplied by the user, based on the Gavscar Gaming video and supporting community references\./gi, 'Neverwinter Workshop Rank 1 → Rank 4 progression notes based on the Gavscar Gaming video and supporting community references.'],
  [/No item-specific evidence lines are attached beyond the catalog source record\./gi, 'No additional notes are attached to this recipe.'],
  [/screenshot-backed/gi, 'verified'],
  [/screenshot backed/gi, 'verified'],
  [/AI-generated/gi, 'curated'],
  [/AI generated/gi, 'curated'],
  [/generated by AI/gi, 'curated'],
  [/developed by AI/gi, 'maintained'],
  [/user-supplied/gi, 'curated'],
  [/supplied screenshot/gi, 'reference'],
  [/latest-user-screenshot/gi, 'verified'],
  [/spreadsheet-supplemental/gi, 'reviewed'],
  [/sharandar-screenshot[^\s]*/gi, 'verified'],
  [/final-zip[^\s]*/gi, 'verified'],
  [/screenshot unavailable/gi, 'reference image unavailable'],
]

function rewrite(value: string) {
  const trimmed = value.trim()
  const exactMatch = exact.get(trimmed)
  let next = exactMatch ? value.replace(trimmed, exactMatch) : value
  for (const [pattern, replacement] of phrases) {
    next = next.replace(pattern, replacement as string)
  }
  return next
}

function prettyReference(value: string) {
  const normalized = value.toLowerCase()
  if (
    normalized.includes('.png') ||
    normalized.includes('.jpg') ||
    normalized.includes('.jpeg') ||
    normalized.includes('.webp') ||
    normalized.includes('.zip') ||
    normalized.includes('evidence/') ||
    normalized.includes('sharandar.zip')
  ) {
    return normalized.includes('sharandar') ? 'Sharandar collection reference' : 'Underdark collection reference'
  }
  return rewrite(value)
}

function processElement(root: ParentNode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  const textNodes: Text[] = []
  while (walker.nextNode()) textNodes.push(walker.currentNode as Text)

  for (const node of textNodes) {
    const parent = node.parentElement
    if (!parent || parent.closest('script, style, code, pre')) continue
    const next = rewrite(node.data)
    if (next !== node.data) node.data = next
  }

  for (const element of Array.from(root.querySelectorAll<HTMLElement>('[aria-label], [title], [placeholder]'))) {
    for (const attr of ['aria-label', 'title', 'placeholder']) {
      const value = element.getAttribute(attr)
      if (!value) continue
      const next = rewrite(value)
      if (next !== value) element.setAttribute(attr, next)
    }
  }

  for (const item of Array.from(root.querySelectorAll<HTMLElement>('.evidence-card li'))) {
    const next = prettyReference(item.textContent || '')
    if (next !== item.textContent) item.textContent = next
  }

  for (const value of Array.from(root.querySelectorAll<HTMLElement>('.evidence-grid strong'))) {
    const next = prettyReference(value.textContent || '')
    if (next !== value.textContent) value.textContent = next
  }

  for (const list of Array.from(root.querySelectorAll<HTMLElement>('.evidence-card ul'))) {
    const seen = new Set<string>()
    for (const item of Array.from(list.querySelectorAll<HTMLElement>(':scope > li'))) {
      const key = (item.textContent || '').trim().toLowerCase()
      if (!key) continue
      if (seen.has(key)) item.hidden = true
      else seen.add(key)
    }
  }
}

export function ContentVoice() {
  useEffect(() => {
    const root = document.querySelector('#root')
    if (!root) return

    let frame = 0
    const schedule = () => {
      if (frame) cancelAnimationFrame(frame)
      frame = requestAnimationFrame(() => {
        frame = 0
        processElement(root)
      })
    }

    processElement(root)
    const observer = new MutationObserver(schedule)
    observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true })

    return () => {
      if (frame) cancelAnimationFrame(frame)
      observer.disconnect()
    }
  }, [])

  return null
}
