export const masterworkDesignDNA = {
  meta: {
    name: 'Masterwork Vault Precision Arcana',
    description: 'A trustworthy game-companion interface: technical clarity first, restrained arcane depth second.',
    source_references: ['Current Masterwork Vault production UI', 'Screenshot evidence workflow', 'Accessibility and performance design standards'],
    created_at: '2026-08-11',
  },
  design_system: {
    color: {
      palette_type: 'cool neutral with arcane blue accent',
      primary: { hex: '#0769D7', role: 'primary actions and active navigation' },
      secondary: { hex: '#27405D', role: 'technical hierarchy and secondary emphasis' },
      accent: { hex: '#7A5AF8', role: 'rare magical/progression accent only' },
      neutral: { scale: ['#FFFFFF', '#F7F8FA', '#ECEEF2', '#D7DAE0', '#6B7280', '#22252A', '#111318'], usage: 'layered surfaces and readable text' },
      semantic: { success: '#167A50', warning: '#9A6700', error: '#B42318', info: '#0769D7' },
      surface: { background: '#F4F5F7', card: '#FFFFFF', elevated: '#FFFFFF' },
      contrast_strategy: 'dark-on-light dominant with semantic text + icon state cues',
    },
    typography: {
      font_families: { heading: 'system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif', body: 'system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif', mono: 'ui-monospace, SFMono-Regular, Menlo, monospace' },
      type_scale: { display: 'clamp(2.2rem, 5vw, 4.8rem)', heading_1: 'clamp(2rem, 4vw, 3.6rem)', heading_2: 'clamp(1.45rem, 2vw, 2.2rem)', heading_3: '1.125rem', body: '1rem', body_small: '.875rem', caption: '.75rem', overline: '.6875rem' },
      font_style_notes: 'system-native, compact labels, tabular numerals for costs and quantities',
    },
    spacing: { base_unit: 4, scale: [4, 8, 12, 16, 24, 32, 48, 64], content_density: 'comfortable with compact option', section_rhythm: '24/32px product sections; 48/64px major page transitions' },
    layout: { grid_system: 'responsive CSS grid', max_content_width: 1480, columns: 12, gutter: 24, breakpoints: [375, 768, 1024, 1440], alignment_tendency: 'strict grid with selective asymmetric hero composition' },
    shape: { border_radius: { small: 8, medium: 12, large: 18, pill: 999 }, border_usage: 'subtle 1px separators', divider_style: 'quiet neutral separators' },
    elevation: { shadow_style: 'soft diffused', levels: { low: '0 2px 8px rgba(20,30,45,.06)', medium: '0 14px 36px rgba(20,30,45,.10)', high: '0 28px 80px rgba(8,18,35,.18)' }, depth_cues: 'surface contrast + restrained shadows + rare blur' },
    iconography: { style: 'outline', stroke_weight: 2, size_scale: [16, 18, 20, 24], preferred_set: 'Lucide' },
    motion: { easing: 'cubic-bezier(.2,0,0,1)', duration_scale: { micro: 140, normal: 260, macro: 440 }, entrance_pattern: '12–20px translate + opacity', exit_pattern: 'shorter ease-in fade/translate', philosophy: 'functional continuity with restrained fantasy ambience' },
    components: { button_style: 'high-contrast primary, quiet secondary, clear focus ring', input_style: '44px minimum with visible labels', card_style: 'white technical surfaces with subtle border and 12–18px radius', navigation_pattern: 'stable route navigation with command palette', modal_style: 'shared accessible dialog/drawer primitives', list_style: 'dense but scannable rows with source/status metadata', component_notes: 'never encode verification state by color alone' },
  },
  design_style: {
    aesthetic: { mood: ['precise', 'calm', 'arcane', 'trustworthy'], visual_metaphor: 'a clean vault ledger with a faint magical instrument panel beneath it', era_influence: 'modern technical dashboard with restrained fantasy ornament', genre: 'game companion / knowledge tool', personality_traits: ['meticulous', 'confident', 'useful'], adjectives: ['clear', 'grounded', 'polished', 'quietly magical'] },
    visual_language: { complexity: 'moderate', ornamentation: 'subtle accents', whitespace_usage: 'comfortable', visual_weight_distribution: 'data first, effects behind content', focal_strategy: 'progressive reveal', contrast_level: 'high for content, soft for decoration', texture_usage: 'very restrained grain/glow only' },
    composition: { hierarchy_method: 'typographic scale + spatial isolation + status chips', balance_type: 'mostly asymmetric', flow_direction: 'top-to-bottom task flow', grouping_strategy: 'cards by player decision', negative_space_role: 'separates planning modes and verification context' },
    imagery: { photo_treatment: 'authentic screenshot-derived assets only', illustration_style: 'no synthetic game art presented as authentic', graphic_elements: 'wireframe sigil / dependency lines', pattern_usage: 'rare geometric vault motif', image_shape: 'square item tiles' },
    interaction_feel: { feedback_style: 'immediate and restrained', hover_behavior: 'surface lift or border emphasis without layout shift', transition_personality: 'decisive glide', loading_style: 'skeleton / stable placeholders', microinteraction_density: 'low-to-medium' },
    brand_voice_in_ui: { tone: 'plain, authoritative, concise', formality: 'professional game-tool', cta_style: 'direct imperative', empty_state_approach: 'explain why + next action', error_tone: 'specific cause and recovery path' },
  },
  visual_effects: {
    overview: { effect_intensity: 'subtle-accent', performance_tier: 'medium', fallback_strategy: 'disable WebGL and spatial motion for reduced-motion or low-end hardware', primary_technology: 'CSS + GSAP + Three.js' },
    background_effects: { type: 'generative wireframe sigil', technology: 'Three.js', description: 'Sparse vault-like geometry behind the hero, never competing with text.' },
    particle_systems: { enabled: true, type: 'sparse constellation points', description: 'Low-count points orbit the sigil slowly.' },
    '3d_elements': { enabled: true, type: 'scene-bg', description: 'Low-poly arcane vault glyph used only in the hero.', technology: 'Three.js' },
    shader_effects: { enabled: false, type: 'none' },
    scroll_effects: { parallax: { enabled: false }, scroll_triggered_animations: { enabled: true, animation_type: 'fade-up', scrub_behavior: 'triggered' }, scroll_morphing: { enabled: false } },
    text_effects: { type: 'none' }, cursor_effects: { enabled: false, type: 'none' }, image_effects: { type: 'none' },
    glassmorphism_neumorphism: { enabled: true, style: 'frosted-layers', description: 'Only on navigation/overlay chrome, not core data cards.' },
    canvas_drawings: { enabled: false, type: 'none' }, svg_animations: { enabled: false, type: 'none' },
    composite_notes: 'The visual-effects layer is deliberately subordinate to evidence-heavy crafting content. No continuous decorative effect is required for usability.',
  },
} as const
