import { expect, test } from '@playwright/test'

const progressKey = 'masterwork-vault.workshop-journey.v2'

test('journey preserves old milestones and deep-links the selected chapter', async ({ page }) => {
  await page.addInitScript((key) => localStorage.setItem(key, JSON.stringify(['foundation','chultan','not-a-real-stage'])), progressKey)
  await page.goto('/journey?stage=workshop')
  await expect(page.locator('.journey-roadmap-step')).toHaveCount(9)
  await expect(page.locator('.journey-personal-progress')).toContainText('2')
  await expect(page.locator('#journey-active-heading')).toHaveText('Progress Workshop ranks and the trading-company story')
  await expect(page.locator('.journey-chapter')).toContainText('2,500,000')
  await expect(page.locator('.journey-chapter a[href*="11548793"]').first()).toBeVisible()
  await page.locator('.journey-roadmap-step').filter({ hasText: 'Chultan I & II' }).click()
  await expect(page.locator('#journey-active-heading')).toHaveText('Acquire Chultan Masterwork I, then II')
  await expect(page.locator('.journey-milestone button')).toHaveAttribute('aria-pressed','true')
  await expect(page).toHaveURL(/stage=chultan/)
  await page.reload()
  await expect(page.locator('#journey-active-heading')).toHaveText('Acquire Chultan Masterwork I, then II')
})

test('journey uses all captured outputs without inventing missing recipes', async ({ page }) => {
  await page.goto('/journey')
  const library = page.locator('#journey-craftables')
  await expect(library).toContainText('110 item records')
  await expect(library).toContainText('145 recipe records')
  await expect(library).toContainText('not every recipe in the game')
  await expect(library.locator('.journey-output')).toHaveCount(30)
  await expect(library.locator('.journey-output-detail')).toHaveCount(0)
  await library.getByRole('button', { name: /Show 30 more/ }).click()
  await expect(library.locator('.journey-output')).toHaveCount(60)
  await library.getByRole('searchbox').fill('Soul Bead')
  const row = library.locator('.journey-output').filter({ has: page.locator('summary strong', { hasText: /^Soul Bead$/ }) })
  await expect(row).toHaveCount(1)
  await row.locator(':scope > summary').click()
  await expect(row).toContainText('2 per successful craft')
  await expect(row.locator('.journey-input-list li')).not.toHaveCount(0)
  await library.getByRole('searchbox').fill('definitely-not-a-real-item')
  await expect(library).toContainText('No captured outputs match')
  await library.getByRole('button', { name: 'Reset craftable filters' }).click()
  await expect(library.locator('.journey-output')).toHaveCount(30)
})


test('standard reference labels Gathering as a legacy pre-compression sample', async ({ page }) => {
  await page.goto('/journey#journey-craftables')
  const library = page.locator('#journey-craftables')
  await library.getByRole('button', { name: /Standard professions/ }).click()
  await library.getByRole('button', { name: 'Gathering evidence (25)', exact: true }).click()
  await expect(library).toContainText('Legacy pre-compression Gathering sample')
  await expect(library).toContainText('old 1–80 profession scale')
  await expect(library).toContainText('2021 compression')
  await expect(library).not.toContainText('complete recorded Level 1-20 Gathering route')
})

test('masterwork research shows publisher corrections and coverage gaps', async ({ page }) => {
  await page.goto('/journey#journey-craftables')
  const library = page.locator('#journey-craftables')
  await library.getByRole('button', { name: /Masterwork research/ }).click()
  await expect(library.getByRole('heading', { name: 'Publisher corrections & coverage gaps' })).toBeVisible()
  await expect(library).toContainText("Hermit's Incense +1")
  await expect(library).toContainText('Item Level 95')
  await expect(library).toContainText('Thorned Amulet +1')
  await expect(library).toContainText('Feywood Amulet +1')
  await expect(library).toContainText("Dawn's Light Sash +1")
  await expect(library).toContainText('Lichstone')
  await expect(library).toContainText('3 Lichstones')
  await expect(library.locator('a[href*="11542223"]')).not.toHaveCount(0)
  await expect(library.locator('a[href*="11500323"]')).not.toHaveCount(0)
})

test('masterwork research reference exposes Chultan formulas without overstating current coverage', async ({ page }) => {
  await page.goto('/journey#journey-craftables')
  const library = page.locator('#journey-craftables')
  await library.getByRole('button', { name: /Masterwork research/ }).click()
  await expect(library).toContainText('18 weapon-slot formulas')
  await expect(library).toContainText('17 intermediate recipes')
  await expect(library).toContainText('Masterwork IV and V')
  await expect(library).toContainText('Menzoberranzan is the latest tier positively documented')
  await expect(library).toContainText('No later tier was verified')
  await expect(library).toContainText('current complete Chultan I / II final-output inventory is not established')
  const publisherLinks = library.locator('a[href*="11500323"]')
  const worksheetLinks = library.locator('a[href*="1gYsenO0JX3fOkZrSxgyJ7fdiBPK_dcs96sP3blUra44"]')
  const artificingLinks = library.locator('.masterwork-research-sources a[href*="Masterwork_Artificing"]')
  await expect(publisherLinks.first()).toBeVisible()
  expect(await publisherLinks.count()).toBeGreaterThanOrEqual(2)
  await expect(worksheetLinks).toHaveCount(2)
  await expect(worksheetLinks.first()).toBeVisible()
  await expect(artificingLinks).toHaveCount(1)
  await expect(artificingLinks.first()).toBeVisible()
  await expect(library).toContainText('Lichstone Enamel')
})

for (const width of [320, 768, 1440]) {
  test(`masterwork research reference reflows at ${width}px`, async ({ page }, testInfo) => {
    test.skip(testInfo.project.name === 'phone', 'Explicit viewport matrix runs once')
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/journey#journey-craftables')
    const library = page.locator('#journey-craftables')
    await library.getByRole('button', { name: /Masterwork research/ }).click()
    await library.scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width + 1)
    await expect(library.getByRole('heading', { name: 'Masterwork lineage and Chultan evidence' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`journey-masterwork-research-${width}.png`) })
  })
}

test('masterwork research exposes the historical Chultan task-table snapshot without calling it current', async ({ page }) => {
  await page.goto('/journey#journey-craftables')
  const library = page.locator('#journey-craftables')
  await library.getByRole('button', { name: /Masterwork research/ }).click()
  await expect(library).toContainText('76 historical IV/V task rows')
  await expect(library).toContainText('Historical Chultan task-table snapshot')
  await expect(library).toContainText('5 worksheet ratios disagree')
  await expect(library).toContainText('Brilliant Bead, Chultan Silk Thread, Fanged Ornament, Lacquered Dinosaur Leather, Lion Fur')
  const search = library.getByRole('searchbox', { name: 'Search Chultan evidence' })
  await search.fill('Commissioned Tyrannosaur Barding')
  const task = library.locator('.masterwork-historical-task').filter({ hasText: 'Commissioned Tyrannosaur Barding' })
  await expect(task).toHaveCount(1)
  await expect(task).toContainText('Armorsmithing · Masterwork IV')
  await task.locator(':scope > summary').click()
  await expect(task).toContainText('Titansteel Plate')
  await expect(task).toContainText('×3')
  await expect(task.getByRole('link', { name: /Open profession task table/ })).toHaveAttribute('href', 'https://neverwinter.fandom.com/wiki/Masterwork_Armorsmithing_page_2')
  await expect(task).toContainText('Historical reference only')
})

test('journey budgets are published scenarios and paid morale needs an entered rate', async ({ page }) => {
  await page.goto('/journey#journey-planning')
  const planning = page.locator('#journey-planning')
  await expect(planning).toContainText('28,000,000 AD')
  await planning.getByRole('spinbutton', { name: 'Professions to budget for' }).fill('1')
  await expect(planning.locator('.journey-planning-total').first()).toContainText('4,000,000 AD')
  await expect(planning).toContainText('Enter the live quote')
  await planning.getByRole('spinbutton', { name: 'Current AD per point' }).fill('100')
  await expect(planning).toContainText('10,000 AD')
  await planning.getByRole('checkbox').check()
  await expect(planning.locator('.journey-planning-total').nth(1)).toContainText('80')
  await expect(planning).toContainText('does not double task XP')
})

test('data health has visual coverage without mislabeling reference icons as game art', async ({ page }) => {
  await page.goto('/data-health')
  const missingArtwork = page.locator('.mw-health-metrics article').filter({ hasText: 'Missing artwork' })
  await expect(missingArtwork).toContainText('0')
  const provenance = page.locator('.mw-health-panel').filter({ hasText: 'Artwork provenance' })
  await expect(provenance).toContainText('reference-derived')
  await expect(provenance).toContainText('Reference-derived visuals preserve layout continuity but are not authentic Neverwinter artwork')
})

test('source-backed and uncertain rules are distinguished in the evidence ledger', async ({ page }) => {
  await page.goto('/data-health')
  await expect(page.locator('.mw-ledger')).toContainText('Current quote required')
  await expect(page.locator('.mw-ledger')).toContainText('Reviewed')
  await expect(page.locator('.mw-ledger')).not.toContainText('120 AD / Morale')
  await expect(page.locator('.mw-ledger tr').filter({ hasText: 'Current Morale refill rate' }).locator('.mw-status-chip')).toHaveText('unknown')
})

for (const width of [320,768,1440]) {
  test(`journey guide and expanded recipe stay usable at ${width}px`, async ({ page },testInfo) => {
    test.skip(testInfo.project.name === 'phone', 'Explicit viewport matrix runs once')
    await page.setViewportSize({ width, height:900 })
    await page.goto('/journey?stage=menzoberranzan')
    await expect(page.locator('#journey-active-heading')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1)
    await page.screenshot({ path:testInfo.outputPath(`journey-overview-${width}.png`) })
    const library=page.locator('#journey-craftables')
    await library.getByRole('searchbox').fill('Soul Bead')
    const row=library.locator('.journey-output').filter({ has: page.locator('summary strong',{hasText:/^Soul Bead$/}) })
    await row.locator(':scope > summary').click()
    await row.scrollIntoViewIfNeeded()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1)
    await page.screenshot({ path:testInfo.outputPath(`journey-recipe-${width}.png`) })
  })
}
